### ISSUE TITLE
Unable to build this package

### ISSUE THREAD

**Issue by copenat** [wso2-ballerina/module-mongodb#37]
**Description:**
The instructions state that I can bypass building from source but I don't see how.  Trying to build this package on Windows 7 I get checkstyle errors. I have used -Dcheckstyle.skip to get around this. But then I get errors with the tests. There are no instructions to set up the tests so I skip them also (-Dmaven.test.skip=true).
Then I try the install.bat which fails so I manually perform the copy of the two files as it suggests but then I get errors from Composer when I import wso2/mongodb as per the code example.

**Comment by copenat** [comment]
https://files.slack.com/files-pri/T47EAEKB5-FDFRMA333/image.png

**Comment by copenat** [comment]
Working with the Ballerina team I used a previous release (0.6.0) as I'm using Ballerina (0.981.0). The install.bat worked fine but the run error remaind. To fix that I copied the mongodb.zip into my users .ballerina repo area and it worked! The checkstyle errors and tests still need fixing though! :)

**Comment by Manuri** [comment]
As discussed on slack as well, https://github.com/ballerina-platform/ballerina-lang/issues/8314 is fixed therefore you shouldn't get the error `could not find package wso2/mongodb:*` anymore.

We will fix the checkstyle issues. On a separate note, you don't have to build the package from source in order to use it. You can download the released package from GitHub [releases](https://github.com/wso2-ballerina/package-mongodb/releases).
